### ISSUE TITLE
Using same session across several chats

### ISSUE THREAD

**Issue by Raingerlina** [telegraf/telegraf-session-redis#17]
Hello!

Currently, I'm using the chat-wide session that you provided earlier and wondering if it is possible to use the same session for several chats with pre-determined ids.

Something like
if (ctx.message.chat.id === "-123123" || ctx.message.chat.id === "-156456")
  session = something similar;

**Comment by dotcypress** [comment]
Hey @Raingerlina 

To achieve shared chat session you can implement custom session key resolver. 
Something like:

```js
const redisSession = new RedisSession({
  getSessionKey: (ctx) => {
     if (!ctx.chat) {
      return
    }
    if (ctx.chat.id === '-123123' || ctx.chat.id === '-156456'){
       return '-123123:-156456' 
    }
    return ctx.chat.id
  }
})
```

**Comment by Raingerlina** [comment]
Thanks for the help, @dotcypress!

Best wishes
