### ISSUE TITLE
Accesssing session without having a chat interaction

### ISSUE THREAD

**Issue by mischkew** [telegraf/telegraf-session-redis#2]
Hey @dotcypress,

first things first: I like what you do here. Really clean design and nice to use! I play around a little with the telegram api and your framework feels very elegant.

Currently I try to do a Pocket integration. Therefore I need to do oauth. The pocket api will execute a callback by accessing a redirect uri. From there, I want to store the access authentication token into the users session. But this uri is out of the context of the current session. As the redis session is stored as soon as all middleware runs through, I cannot use local scoping either. Do you have any ideas how to solve this with the current architecture?

If not I have some ideas for a solution:

1) setup a separate session store and sync with redis in session (feels bulky)
2) setup a 2nd client to the same redis session and insert access token via that global client (I know the session key. But also this feels weird...)
3) (my preference) export the redis session store so it is accessible outside a chat interaction. This needs altering to your code. Would also be useful for the in-memory session.

What do you think? I could provide a PR for 3).

Cheers
Sven

**Comment by dotcypress** [comment]
Hey @mischkew

Thank you for your feedback. 👍

Solution 3 was implemented and published as `4.0.0`
